-- CreateTable
CREATE TABLE `SBTRequest` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `to` VARCHAR(42) NOT NULL,
    `tokenId` VARCHAR(191) NOT NULL,
    `uri` VARCHAR(191) NOT NULL,
    `deadline` BIGINT NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SignedSBT` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `to` VARCHAR(42) NOT NULL,
    `tokenId` VARCHAR(191) NOT NULL,
    `uri` VARCHAR(191) NOT NULL,
    `deadline` BIGINT NOT NULL,
    `signature` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
